// Generated by Wrangler on Thu Jun 13 2024 08:37:45 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	ENVIRONMENT: "dev";
	CONFERENCE_NAME: "MERGE";
	workers_dev: true;
	DATABASE_URL: string;
}
