name: PR Preview Cleanup
on:
  pull_request:
    types: [closed]

env:
  PREVIEW_NAME: pr-${{ github.event.number }}

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      # generate the environment in the wrangler.toml
      - run: npm run preview -- ${{ env.PREVIEW_NAME }}

      # delete neon branch
      - uses: neondatabase/delete-branch-action@v3.1.3
        continue-on-error: true
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: preview/${{ env.PREVIEW_NAME }}
          api_key: ${{ secrets.NEON_API_KEY }}

      # delete worker preview
      - uses: cloudflare/wrangler-action@v3
        continue-on-error: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: delete --env ${{ env.PREVIEW_NAME }}
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
